import type { NextPage } from 'next'
import Head from 'next/head'
import Masthead from '../components/masthead'
import AboutUs from '../components/aboutus'
import Skills from '../components/skills'
import useSWR from 'swr'

const fetcher = (input: any, init?: any) =>
  fetch(input, init).then((res) => res.json());

const Home: NextPage = () => {
 const { data } = useSWR("/api/stats", fetcher);
  return (
    <div >
      <Head>
        <title>UBT Agency</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Masthead />
      <AboutUs />
      <Skills commits={data?.commits} /> 
    </div>
  )
}

export default Home
